"""add dashboard_layout to modules

Revision ID: 152a8e11d85a
Revises: e606b7bcf992
Create Date: 2026-10-04 11:25:35.932675

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '152a8e11d85a'
down_revision: str | Sequence[str] | None = 'e606b7bcf992'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('dashboard_layout', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'dashboard_layout')
    # ### end Alembic commands ###
