"""add theme_mode and skin to app_settings

Revision ID: 32913aa97e2f
Revises: c7591554ca31
Create Date: 2026-09-17 23:10:38.676640

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '32913aa97e2f'
down_revision: str | Sequence[str] | None = 'c7591554ca31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'app_settings', sa.Column('theme_mode', sa.String(length=10), nullable=False, server_default='system')
    )
    op.add_column('app_settings', sa.Column('skin', sa.String(length=20), nullable=False, server_default='default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'skin')
    op.drop_column('app_settings', 'theme_mode')
    # ### end Alembic commands ###
