"""add calendar feeds

Revision ID: 337263758a1b
Revises: 7df4efe8abae
Create Date: 2026-10-04 12:25:30.058576

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '337263758a1b'
down_revision: str | Sequence[str] | None = '7df4efe8abae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_feed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['calendar_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_feed_events_feed_id_starts_at', 'calendar_feed_events', ['feed_id', 'starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calendar_feed_events_feed_id_starts_at', table_name='calendar_feed_events')
    op.drop_table('calendar_feed_events')
    op.drop_table('calendar_feeds')
    # ### end Alembic commands ###
