"""add dashboard_layout to app_settings

Revision ID: 3dd0d71c0e03
Revises: a3f1c7d2e905
Create Date: 2026-10-01 21:45:25.821705

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3dd0d71c0e03'
down_revision: str | Sequence[str] | None = 'a3f1c7d2e905'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('dashboard_layout', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'dashboard_layout')
    # ### end Alembic commands ###
