"""add table_alignment, note_font_size, keybinds to app_settings

Revision ID: 4d7bad042f9d
Revises: 32913aa97e2f
Create Date: 2026-09-19 14:10:29.744226

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d7bad042f9d'
down_revision: str | Sequence[str] | None = '32913aa97e2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'app_settings', sa.Column('table_alignment', sa.String(length=10), nullable=False, server_default='left')
    )
    op.add_column('app_settings', sa.Column('note_font_size', sa.Integer(), nullable=False, server_default='15'))
    op.add_column(
        'app_settings', sa.Column('keybind_bold', sa.String(length=20), nullable=False, server_default='Mod-b')
    )
    op.add_column(
        'app_settings', sa.Column('keybind_italic', sa.String(length=20), nullable=False, server_default='Mod-i')
    )
    op.add_column(
        'app_settings', sa.Column('keybind_code', sa.String(length=20), nullable=False, server_default='Mod-e')
    )
    op.add_column(
        'app_settings',
        sa.Column('keybind_wikilink', sa.String(length=20), nullable=False, server_default='Mod-Shift-k'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'keybind_wikilink')
    op.drop_column('app_settings', 'keybind_code')
    op.drop_column('app_settings', 'keybind_italic')
    op.drop_column('app_settings', 'keybind_bold')
    op.drop_column('app_settings', 'note_font_size')
    op.drop_column('app_settings', 'table_alignment')
    # ### end Alembic commands ###
