"""calendar feed files and linked lectures

Revision ID: 50ae9887823c
Revises: 337263758a1b
Create Date: 2026-10-04 12:50:10.835507

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50ae9887823c'
down_revision: str | Sequence[str] | None = '337263758a1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_feed_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['calendar_feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'title')
    )
    op.add_column('calendar_feeds', sa.Column('source_text', sa.Text(), nullable=True))
    op.alter_column('calendar_feeds', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('lectures', sa.Column('feed_id', sa.Integer(), nullable=True))
    op.add_column('lectures', sa.Column('feed_uid', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_lectures_feed_id'), 'lectures', ['feed_id'], unique=False)
    op.create_unique_constraint('lectures_feed_id_feed_uid_key', 'lectures', ['feed_id', 'feed_uid'])
    op.create_foreign_key(
        'lectures_feed_id_fkey', 'lectures', 'calendar_feeds', ['feed_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Lectures synced from feeds and uploaded-file feeds can't exist in the old schema.
    op.execute("DELETE FROM lectures WHERE feed_id IS NOT NULL")
    op.execute("DELETE FROM calendar_feeds WHERE url IS NULL")
    op.drop_constraint('lectures_feed_id_fkey', 'lectures', type_='foreignkey')
    op.drop_constraint('lectures_feed_id_feed_uid_key', 'lectures', type_='unique')
    op.drop_index(op.f('ix_lectures_feed_id'), table_name='lectures')
    op.drop_column('lectures', 'feed_uid')
    op.drop_column('lectures', 'feed_id')
    op.alter_column('calendar_feeds', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('calendar_feeds', 'source_text')
    op.drop_table('calendar_feed_links')
    # ### end Alembic commands ###
