"""add setup_completed and default_module_layout to app_settings

Revision ID: 711f992b2d9e
Revises: b7e2d4f1a9c3
Create Date: 2026-10-04 16:35:32.506478

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '711f992b2d9e'
down_revision: str | Sequence[str] | None = 'b7e2d4f1a9c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('default_module_layout', sa.JSON(), nullable=True))
    op.add_column('app_settings', sa.Column('setup_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
    # An install that already has modules isn't a first run: don't send it to the setup page.
    op.execute(
        "UPDATE app_settings SET setup_completed = true WHERE EXISTS (SELECT 1 FROM modules)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'setup_completed')
    op.drop_column('app_settings', 'default_module_layout')
    # ### end Alembic commands ###
