"""add submodule_links

Revision ID: 7c1025ad6f88
Revises: 32913aa97e2f
Create Date: 2026-09-18 21:00:52.843419

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c1025ad6f88'
down_revision: str | Sequence[str] | None = '32913aa97e2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submodule_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_submodule_id', sa.Integer(), nullable=False),
    sa.Column('target_submodule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_submodule_id'], ['submodules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_submodule_id'], ['submodules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_submodule_id', 'target_submodule_id')
    )
    op.create_index(op.f('ix_submodule_links_source_submodule_id'), 'submodule_links', ['source_submodule_id'], unique=False)
    op.create_index(op.f('ix_submodule_links_target_submodule_id'), 'submodule_links', ['target_submodule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submodule_links_target_submodule_id'), table_name='submodule_links')
    op.drop_index(op.f('ix_submodule_links_source_submodule_id'), table_name='submodule_links')
    op.drop_table('submodule_links')
    # ### end Alembic commands ###
