"""add module notes, banner and module to-dos

Revision ID: 7df4efe8abae
Revises: 152a8e11d85a
Create Date: 2026-10-04 11:39:12.972083

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7df4efe8abae'
down_revision: str | Sequence[str] | None = '152a8e11d85a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('banner', sa.JSON(), nullable=True))
    op.add_column('quick_todos', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_foreign_key('quick_todos_module_id_fkey', 'quick_todos', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quick_todos_module_id_fkey', 'quick_todos', type_='foreignkey')
    op.drop_column('quick_todos', 'module_id')
    op.drop_column('modules', 'banner')
    op.drop_column('modules', 'notes')
    # ### end Alembic commands ###
